include $(GOROOT)/src/Make.inc

# TARG=github.com/Gastrograph/rsc/imap

TARG=rsc.googlecode.com/hg/imap
GOFILES=\
	decode.go\
	imap.go\
	mail.go\
	sx.go\
	tcs.go\

GCIMPORTS=-I$(GOPATH)/pkg/$(GOOS)_$(GOARCH)

include $(GOROOT)/src/Make.pkg
